- src/app/pubScreen/pubScreen.component.ts
> removing console log

- Services/PubScreenService.cs
- Services/UploadService.cs
(2) CPT hit rate/false alarm rate calculations fixed
(3) New CPT session added
> (1) Pubscreen delete fixed

- src/app/app.component.html
- src/app/home/home.component.html
- src/app/home/home.component.ts
Adding `alt` attribute to the MouseBytes Logo, and the image in the center of the home page
> AOD missing image alternative

- Services/PubScreenService.cs
> add proxy to httpclient

- Services/HelperService.cs
- src/app/data-extraction/data-extraction.component.ts
Modified code to incorporate Dat-IRES-Cre line
> Added Dat-Cre Strain/Genotype

- Controllers/CogbytesController.cs
- Controllers/SearchExpController.cs
Added MIME application type for 7z archive
> Added support for 7z archives

- Services/PubScreenService.cs
- src/app/cogbytesUpload/cogbytesUpload.component.ts
adds the correct field to search for elastic search and fix cogbytes upload drop down menu
> Fix sub model search

- Services/PubScreenService.cs
Remove ToLower on all strings and add GUID to the papers
> remove toLower and add guid to results

- CBAS.csproj
This reverts commit fb3906fec19ce5c365e2cd9f7778eac1c31f3d79.
> Revert "Update CBAS.csproj (#72)"

- CBAS.csproj
- Controllers/PubScreenController.cs
- Data/Dal.cs
- Services/PubScreenService.cs
- Startup.cs
- appsettings.json
- src/app/pubScreen/pubScreen.component.ts
- src/app/services/pubScreen.service.ts
- web.config
Upgrade dotnet framework to 8.0
Installed Microsoft.TypeScript.MSBuild
Fixing some breaking code
> Upgrading dotnet and related libraries

- Controllers/AnimalController.cs
- Controllers/CogbytesController.cs
- Controllers/ExperimentController.cs
- Controllers/IdentityController.cs
- Controllers/PISiteController.cs
- Controllers/ProfileController.cs
- Controllers/PubScreenController.cs
- Controllers/UploadController.cs
- Data/Dal.cs
Removed unused code
Used async await
Cleaned up
> Removed unused code, Used async await, Cleaned up

- CBAS.csproj
This reverts commit 83ad2a99b88c8aa818502045ea1628d1c9d9b709.
> Revert "Upgrade nuget packages and added depricated navigator (#92)"

- Controllers/AnimalController.cs
- Data/Dal.cs
- Services/AnimalService.cs
AnimalService class db calls all refactore
> prevent sql injection and refactoring

- Controllers/PubScreenController.cs
- Data/Dal.cs
- Services/PubScreenService.cs
ProcCmdAsync, GetDataTablePubAsync, and refactoring some PubScreen methods to use them
> PubScreenService-refactoring

- src/app/pubScreen/pubScreen.component.ts
show spinner for pubscreen search
> show spinner after pubscreen search

- angular.json
set the output folder to wwwroot
> do not include anything in browser folder

- Services/HelperService.cs
- src/app/data-extraction/data-extraction.component.ts
Addition of new genotypes to M83-Hemi-PFF strain. Support database changes.
> Added logic for new M83 groups

- Services/HelperService.cs
Add error log to send email method
> add error log to sendEmail

- Config.cs
- Program.cs
- Properties/launchSettings.json
- README.md
- Startup.cs
- protractor.conf.js
- proxy.config.js
- src/app/cogbytes/cogbytes.component.html
- src/app/cogbytes/cogbytes.component.ts
- src/app/cogbytesEdit/cogbytesEdit.component.html
- src/app/cogbytesSearch/cogbytesSearch.component.html
- src/app/cogbytesSearch/cogbytesSearch.component.ts
- src/app/cogbytesUpload/cogbytesUpload.module.ts
- src/app/data-extraction/data-extraction.component.ts
- src/app/oauth.config.ts
- src/app/pubScreen/pubScreen.component.html
- src/app/pubScreen/pubScreen.component.ts
- src/app/pubScreenEdit/pubScreenEdit.component.html
- src/app/pubScreenQueue/pubScreenQueue.component.ts
- src/app/pubscreenDialoge/pubscreenDialoge.component.html
- src/app/shared-experiment/shared-experiment.component.html
- src/app/upload/upload.module.ts
replace localhost with the correct url
> add correct URL

- src/styles/app.scss
Initially the tooltip appeared in the middle blocking the ability to select other option on the menu:
After:
> show tool tip to the left

- Controllers/IdentityController.cs
- Controllers/PISiteController.cs
- Services/PISiteService.cs
- src/app/account/signup/signup.component.html
- src/app/profile/profile.component.html
- src/app/profile/profile.component.ts
- src/app/profile/profile.module.ts
- src/app/services/piSite.service.ts
Updated handling of user accounts:
- PI requirement removed from Sign Up
- Ability to delete PISite associations on Profile
- Added API to handle deletion.
> Remove site requirement

- Startup.cs
Reverts Rodent-Cognition-Core/CBAS#211
> Revert "Fix identity server"
